var store = function() {
	this.left = '<div class="app-field clearfix editing module_div">'
			+ '	  <div class="control-group">'
			+ '		<div class="custom-store block-item">'
			+ '			<a class="custom-store-link clearfix" href='+getRootPath()+'/mall">'
			+ '			<div class="custom-store-img"></div>'
			+ '			<div class="custom-store-name">' 
			+ '			微信商城   '
			+ '			</div>'
			+ '			</a>' 
			+ '		</div>'
			+ '		<div class="component-border"></div>' 
			+ '	</div>'
			+ '	<div class="actions">' 
			+ '	<div class="actions-wrap">'
			//+ '		<span class="action edit">编辑</span>'
			//+ '		<span class="action add">加内容</span>'
			+ '		<span class="action delete">删除</span>' 
			+ '	 </div>'
			+ '  </div>' 
			+ '	<div class="sort">'
			+ '		<i class="sort-handler"></i>' 
			+ '	</div>' 
			+ '	</div>'

	this.right = '	<div class="app-sidebar">' 
			+ '		<div class="arrow"></div>'
			+ '		<div class="app-sidebar-inner js-sidebar-region"><div>'
			+ '		<div class="app-component-desc">'
			+ '		<p>进入店铺</p>'
			+ '	    </div>' 
			+ '	</div></div>' 
			+ '	</div> '
}
